// components/ConnectionIndicator.tsx - Shows offering-spec connections
import { Badge } from "@/components/ui/badge";
import { Link, ArrowRight, RefreshCw } from "lucide-react";

interface ConnectionIndicatorProps {
  hasLinkedSpec?: boolean;
  linkedSpecId?: string;
  isAutoGenerated?: boolean;
  showSyncStatus?: boolean;
  className?: string;
}

export const ConnectionIndicator: React.FC<ConnectionIndicatorProps> = ({
  hasLinkedSpec = false,
  linkedSpecId,
  isAutoGenerated = false,
  showSyncStatus = false,
  className = ""
}) => {
  if (!hasLinkedSpec && !isAutoGenerated) {
    return null;
  }

  return (
    <div className={`flex items-center gap-2 ${className}`}>
      {hasLinkedSpec && (
        <Badge variant="outline" className="text-xs bg-blue-50 text-blue-700 border-blue-200">
          <Link className="w-3 h-3 mr-1" />
          Linked Spec
        </Badge>
      )}
      
      {isAutoGenerated && (
        <Badge variant="outline" className="text-xs bg-green-50 text-green-700 border-green-200">
          <ArrowRight className="w-3 h-3 mr-1" />
          Auto-Generated
        </Badge>
      )}
      
      {showSyncStatus && hasLinkedSpec && (
        <Badge variant="outline" className="text-xs bg-purple-50 text-purple-700 border-purple-200">
          <RefreshCw className="w-3 h-3 mr-1" />
          Auto-Sync
        </Badge>
      )}
    </div>
  );
};